// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetOidcConfigOperation   OperationName = "GetOidcConfig"
	GetUserinfoOperation     OperationName = "GetUserinfo"
	ListIngressInfoOperation OperationName = "ListIngressInfo"
)
