// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetOidcConfig implements getOidcConfig operation.
//
// Get OIDC configuration.
//
// GET /oidc-config
func (UnimplementedHandler) GetOidcConfig(ctx context.Context) (r *OIDCConfig, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserinfo implements getUserinfo operation.
//
// Get userinfo from OIDC provider.
//
// GET /userinfo
func (UnimplementedHandler) GetUserinfo(ctx context.Context) (r GetUserinfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListIngressInfo implements listIngressInfo operation.
//
// List ingress info.
//
// GET /list
func (UnimplementedHandler) ListIngressInfo(ctx context.Context) (r []IngressInfo, _ error) {
	return r, ht.ErrNotImplemented
}
