// Code generated by ogen, DO NOT EDIT.

package api

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/IngressInfo
type IngressInfo struct {
	Name    string   `json:"name"`
	URL     string   `json:"url"`
	IconURL string   `json:"icon_url"`
	Tags    []string `json:"tags"`
}

// GetName returns the value of Name.
func (s *IngressInfo) GetName() string {
	return s.Name
}

// GetURL returns the value of URL.
func (s *IngressInfo) GetURL() string {
	return s.URL
}

// GetIconURL returns the value of IconURL.
func (s *IngressInfo) GetIconURL() string {
	return s.IconURL
}

// GetTags returns the value of Tags.
func (s *IngressInfo) GetTags() []string {
	return s.Tags
}

// SetName sets the value of Name.
func (s *IngressInfo) SetName(val string) {
	s.Name = val
}

// SetURL sets the value of URL.
func (s *IngressInfo) SetURL(val string) {
	s.URL = val
}

// SetIconURL sets the value of IconURL.
func (s *IngressInfo) SetIconURL(val string) {
	s.IconURL = val
}

// SetTags sets the value of Tags.
func (s *IngressInfo) SetTags(val []string) {
	s.Tags = val
}
