// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetOidcConfig implements getOidcConfig operation.
	//
	// Get OIDC configuration.
	//
	// GET /oidc-config
	GetOidcConfig(ctx context.Context) (*OIDCConfig, error)
	// GetUserinfo implements getUserinfo operation.
	//
	// Get userinfo from OIDC provider.
	//
	// GET /userinfo
	GetUserinfo(ctx context.Context) (GetUserinfoRes, error)
	// ListIngressInfo implements listIngressInfo operation.
	//
	// List ingress info.
	//
	// GET /list
	ListIngressInfo(ctx context.Context) ([]IngressInfo, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
