---
apiVersion: v1
kind: Service
metadata:
  name: kube-portal
  labels:
    app: kube-portal
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kube-portal
