version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
#- package-ecosystem: 'npm'
#  directory: '/client'
#  schedule:
#    interval: 'daily'
#  labels:
#    - "dependencies"
#    - "automerge"
