#
# It's a docker-compose file for building development environment.
#

services:
  backend:
    build:
      context: .
      dockerfile: ./development/backend.dockerfile
    command:
      - --kubeconfig=/mnt/kubeconfig
      - --disable-oidc
    ports:
      - 8080:8080
    volumes:
      - './backend:/app'
      # specify your Kubeconfig filepath
      - '$HOME/.kube/config:/mnt/kubeconfig'

  frontend:
    image: node:24.14-alpine
    volumes:
      - './frontend:/frontend'
    working_dir: /frontend
    entrypoint: sh
    command:
      - -c
      - |
        corepack enable
        pnpm install
        pnpm dev
    environment:
      BACKEND_URL: http://backend:8080
    ports:
      - 3000:3000
