#
# It's a docker-compose file for building development environment.
#

services:
  backend:
    build:
      context: .
      dockerfile: ./development/backend.dockerfile
    command:
      - --kubeconfig=/mnt/kubeconfig
      - --bind-addr=0.0.0.0:3001
      - --development
      - --server-url=http://localhost:3001/
    environment:
      ALLOWED_ORIGIN_URL: http://${SERVER_ADDR}:3000
      OIDC_PROVIDER_URL: ${OIDC_PROVIDER_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      ROLE_ATTRIBUTE_PATH: ${ROLE_ATTRIBUTE_PATH}
    ports:
      - 3001:3001
    volumes:
      - './main.go:/app/main.go'
      - './flag:/app/flag'
      - './backend:/app/backend'
      # specify your Kubeconfig filepath
      - '$HOME/.kube/config:/mnt/kubeconfig'

  frontend:
    image: node:22.21-alpine
    volumes:
      - './frontend:/frontend'
    working_dir: /frontend
    entrypoint: sh
    command:
      - -c
      - |
        yarn install
        yarn dev
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://${SERVER_ADDR}:3001
    ports:
      - 3000:3000
