#
# It's a docker-compose file for building development environment.
#

version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./development/server.dockerfile
    command:
      - --kubeconfig=/mnt/kubeconfig
      - --bind-addr=0.0.0.0:3001
    ports:
      - 3001:3001
    volumes:
      - './cmd:/app/cmd'
      - './server:/app/server'
      # specify your Kubeconfig filepath
      - '$HOME/.kube/config:/mnt/kubeconfig'

  frontend:
    image: node:20.12-alpine
    volumes:
      - './client:/client'
    working_dir: /client
    entrypoint: sh
    command:
      - -c
      - |
        yarn install
        yarn dev
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://${SERVER_ADDR}:3001
    ports:
      - 3000:3000
