#
# It's a docker-compose file for building development environment.
#

version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./development/backend.dockerfile
    command:
      - --kubeconfig=/mnt/kubeconfig
      - --bind-addr=0.0.0.0:3001
    ports:
      - 3001:3001
    volumes:
      - './main.go:/app/main.go'
      - './flag:/app/flag'
      - './backend:/app/backend'
      # specify your Kubeconfig filepath
      - '$HOME/.kube/config:/mnt/kubeconfig'

  frontend:
    image: node:22.16-alpine
    volumes:
      - './frontend:/frontend'
    working_dir: /frontend
    entrypoint: sh
    command:
      - -c
      - |
        yarn install
        yarn dev
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://${SERVER_ADDR}:3001
    ports:
      - 3000:3000
