// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListIngressInfo implements listIngressInfo operation.
//
// List ingress info.
//
// GET /list
func (UnimplementedHandler) ListIngressInfo(ctx context.Context) (r []IngressInfo, _ error) {
	return r, ht.ErrNotImplemented
}
