apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-portal
  name: kube-portal
  namespace: kube-portal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-portal
  name: kube-portal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-portal
subjects:
- kind: ServiceAccount
  name: kube-portal
  namespace: kube-portal
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-portal
  name: kube-portal
  namespace: kube-portal
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-portal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-portal
  name: kube-portal
  namespace: kube-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-portal
  template:
    metadata:
      labels:
        app: kube-portal
    spec:
      containers:
      - image: kanatakita/kube-portal:latest
        name: kube-portal
        ports:
        - containerPort: 8080
      serviceAccountName: kube-portal
