---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-portal
  labels:
    app: kube-portal
subjects:
  - kind: ServiceAccount
    name: kube-portal
    namespace: kube-portal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-portal
