name: Push a new tag when PR with specified labels was merged

on:
  pull_request:
    types: [closed]

jobs:
  tagged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

      - uses: actions/checkout@v4
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          # to trigger release.yml Action
          token: ${{ secrets.TOKEN }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      # switch to `release-vX.X.X` branch & update manifest's tag
      - uses: imranismail/setup-kustomize@v2
      - run: |
          git switch -c release-${{ steps.bump-semver.outputs.new_version }}
          cd manifests/base/
          kustomize edit set image kanatakita/kube-portal:${{ steps.bump-semver.outputs.new_version }}
          cd ..
          kustomize build install/ > ./install.yaml
          git add .
          git config user.email "action@users.noreply.github.com"
          git config user.name "GitHub Action"
          git commit -m "update manifests"
          git push origin HEAD

      - uses: actions-ecosystem/action-push-tag@v1
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
