name: test
on: push
jobs:
  gotest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Go Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

  #jest: # TODO
  #  name: Test
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #      with:
  #        fetch-depth: 1
